# Generated by Django 4.2.23 on 2025-07-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token_created_at',
            field=models.IntegerField(null=True),
        ),
    ]
